config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :faculties, :people, :publications
  get '/', to: 'people#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/faculty.rb
class Faculty < ApplicationRecord
  has_many :publications # 1:N, název cíle píšu plurálně

  validates :name, presence: true
  validates :code, presence: true
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :publications # 1:N, název cíle píšu plurálně

  # Další:
  # has_one <singular> - 1:1
  #
  # M:N:
  # has_many <plural>, through: <plural> - přes explicitní spojovací tabulku (do relace můžeme uvést relátor)
  # has_and_belongs_to_many <plural> - spojovací tabulka se vytvoří implicitně - uvádí se na obou stranách relace

  validates :name, presence: true
  validates :email, presence: true
  validates :username, presence: true

  validates :email, format: { with: /\A[a-z0-9]+@[a-z0-9]+\.[a-z]{2,3}\z/,
                              message: "Vložte platnou e-mailovou adresu." }
end

app/models/publication.rb
class Publication < ApplicationRecord
  # non-owning strana 1:N relace
  # název cíle bude v singuláru - odkazuje na Person, ale píšu to malým
  belongs_to :person, optional: true # povinnost tohoto zajistí view a kontrolér
  belongs_to :faculty, optional: true # povinnost tohoto zajistí view a kontrolér

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/faculties_controller.rb
class FacultiesController < ApplicationController
  before_action :set_faculty, only: [:show, :edit, :update, :destroy]

  # GET /faculties
  # GET /faculties.json
  def index
    @faculties = Faculty.all
  end

  # GET /faculties/1
  # GET /faculties/1.json
  def show
  end

  # GET /faculties/new
  def new
    @faculty = Faculty.new
  end

  # GET /faculties/1/edit
  def edit
  end

  # POST /faculties
  # POST /faculties.json
  def create
    @faculty = Faculty.new(faculty_params)

    respond_to do |format|
      if @faculty.save
        format.html { redirect_to @faculty, notice: 'Faculty was successfully created.' }
        format.json { render :show, status: :created, location: @faculty }
      else
        format.html { render :new }
        format.json { render json: @faculty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /faculties/1
  # PATCH/PUT /faculties/1.json
  def update
    respond_to do |format|
      if @faculty.update(faculty_params)
        format.html { redirect_to @faculty, notice: 'Faculty was successfully updated.' }
        format.json { render :show, status: :ok, location: @faculty }
      else
        format.html { render :edit }
        format.json { render json: @faculty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faculties/1
  # DELETE /faculties/1.json
  def destroy
    @faculty.destroy
    respond_to do |format|
      format.html { redirect_to faculties_url, notice: 'Faculty was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faculty
      @faculty = Faculty.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def faculty_params
      params.require(:faculty).permit(:name, :code, :note)
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
    # produkt čisté zoufalosti, aneb když dotaz z view na kolekci nefunguje
    # kvůli špatnému názvu FK v databázi
    @publications = Publication.where(["people_id = ?", @person.id])
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :email, :username)
    end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_publication, only: [:show, :edit, :update, :destroy]

  # GET /publications
  # GET /publications.json
  def index
    @publications = Publication.all
  end

  # GET /publications/1
  # GET /publications/1.json
  def show
    # produkt čisté zoufalosti, aneb když dotaz z view na kolekci nefunguje
    # kvůli špatnému názvu FK v databázi
    @faculty1 = Faculty.where(["id = ?", @publication.faculties_id])
  end

  # GET /publications/new
  def new
    @publication = Publication.new
  end

  # GET /publications/1/edit
  def edit
  end

  # POST /publications
  # POST /publications.json
  def create

    @publication = Publication.new(publication_params)

    respond_to do |format|
      if @publication.save
        format.html { redirect_to @publication, notice: 'Publication was successfully created.' }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1
  # PATCH/PUT /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to @publication, notice: 'Publication was successfully updated.' }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1
  # DELETE /publications/1.json
  def destroy
    @publication.destroy
    respond_to do |format|
      format.html { redirect_to publications_url, notice: 'Publication was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def publication_params
      params.require(:publication).permit(:name, :published, :abstract, :people_id, :faculties_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/faculties/_form.html.erb
<%= form_with(model: faculty, local: true) do |form| %>
  <% if faculty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(faculty.errors.count, "error") %> prohibited this faculty from being saved:</h2>

      <ul>
        <% faculty.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="field">
    <%= form.label :note %>
    <%= form.text_field :note %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/faculties/edit.html.erb
<h1>Editing Faculty</h1>

<%= render 'form', faculty: @faculty %>

<%= link_to 'Show', @faculty %> |
<%= link_to 'Back', faculties_path %>

app/views/faculties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Faculties</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Code</th>
      <th>Note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @faculties.each do |faculty| %>
      <tr>
        <td><%= faculty.name %></td>
        <td><%= faculty.code %></td>
        <td><%= faculty.note %></td>
        <td><%= link_to 'Show', faculty %></td>
        <td><%= link_to 'Edit', edit_faculty_path(faculty) %></td>
        <td><%= link_to 'Destroy', faculty, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Faculty', new_faculty_path %>

app/views/faculties/new.html.erb
<h1>New Faculty</h1>

<%= render 'form', faculty: @faculty %>

<%= link_to 'Back', faculties_path %>

app/views/faculties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @faculty.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @faculty.code %>
</p>

<p>
  <strong>Note:</strong>
  <%= @faculty.note %>
</p>

<%= link_to 'Edit', edit_faculty_path(@faculty) %> |
<%= link_to 'Back', faculties_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsHw6</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">Rails HW6</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to 'People', people_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Faculties', faculties_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Publications', publications_path, class: 'nav-link' %>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
        <% person.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.email %></td>
        <td><%= person.username %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @person.email %>
</p>

<p>
  <strong>Username:</strong>
  <%= @person.username %>
</p>

<h3>Publications</h3>
<ul>
  <% @publications.each do |p| %>
    <li><%= p.name %></li>
  <% end %>
</ul>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/publications/_form.html.erb
<%= form_with(model: publication, local: true) do |form| %>
  <% if publication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

      <ul>
        <% publication.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :published %>
    <%= form.text_field :published %>
  </div>

  <div class="field">
    <%= form.label :abstract %>
    <%= form.text_field :abstract %>
  </div>

  <div class="field">
    <%= form.label :person %>
    <% people_options = Person.all.map { |p| [p.name, p.id] } %>
    <%= select(:publication, :people_id, people_options) %>
  </div>

  <div class="field">
    <%= form.label :faculty %>
    <% faculty_options = Faculty.all.map { |f| [f.name, f.id] } %>
    <%= select(:publication, :faculties_id, faculty_options) %>
  </div>

  <br>
  <br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/publications/edit.html.erb
<h1>Editing Publication</h1>

<%= render 'form', publication: @publication %>

<%= link_to 'Show', @publication %> |
<%= link_to 'Back', publications_path %>

app/views/publications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Publications</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Published</th>
      <th>Abstract</th>
      <th>Is published?</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @publications.each do |publication| %>
      <tr>
        <td><%= publication.name %></td>
        <td><%= publication.published %></td>
        <td><%= publication.abstract %></td>
        <td><%= publication.published != nil ? "YES" : "NO" %></td>
        <td><%= link_to 'Show', publication %></td>
        <td><%= link_to 'Edit', edit_publication_path(publication) %></td>
        <td><%= link_to 'Destroy', publication, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Publication', new_publication_path %>

app/views/publications/new.html.erb
<h1>New Publication</h1>

<%= render 'form', publication: @publication %>

<%= link_to 'Back', publications_path %>

app/views/publications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @publication.name %>
</p>

<p>
  <strong>Published:</strong>
  <%= @publication.published %>
</p>

<p>
  <strong>Abstract:</strong>
  <%= @publication.abstract %>
</p>

<!-- asociace zase nefunguje -->
<p>
  <strong>Faculty:</strong>
  <%= @faculty1.name %>
</p>

<%= link_to 'Edit', edit_publication_path(@publication) %> |
<%= link_to 'Back', publications_path %>